// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// csm
List csm(double lam1, double lam2, double lam3, double mu1, double mu2, int crown_or_stem, double pp, double t_step);
RcppExport SEXP _csm_csm(SEXP lam1SEXP, SEXP lam2SEXP, SEXP lam3SEXP, SEXP mu1SEXP, SEXP mu2SEXP, SEXP crown_or_stemSEXP, SEXP ppSEXP, SEXP t_stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lam1(lam1SEXP);
    Rcpp::traits::input_parameter< double >::type lam2(lam2SEXP);
    Rcpp::traits::input_parameter< double >::type lam3(lam3SEXP);
    Rcpp::traits::input_parameter< double >::type mu1(mu1SEXP);
    Rcpp::traits::input_parameter< double >::type mu2(mu2SEXP);
    Rcpp::traits::input_parameter< int >::type crown_or_stem(crown_or_stemSEXP);
    Rcpp::traits::input_parameter< double >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< double >::type t_step(t_stepSEXP);
    rcpp_result_gen = Rcpp::wrap(csm(lam1, lam2, lam3, mu1, mu2, crown_or_stem, pp, t_step));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_csm_csm", (DL_FUNC) &_csm_csm, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_csm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
