# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

csm <- function(lam1, lam2, lam3, mu1, mu2, crown_or_stem, pp, t_step) {
    .Call('_csm_csm', PACKAGE = 'csm', lam1, lam2, lam3, mu1, mu2, crown_or_stem, pp, t_step)
}

