# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_reaction <- function(p_lam1, p_lam2, p_lam3, p_mu1, p_mu2) {
    .Call('_csm_get_reaction', PACKAGE = 'csm', p_lam1, p_lam2, p_lam3, p_mu1, p_mu2)
}

choose_random_integer <- function(max_value) {
    .Call('_csm_choose_random_integer', PACKAGE = 'csm', max_value)
}

csm <- function(lam1, lam2, lam3, mu1, mu2, crown_or_stem, pp, t_step) {
    .Call('_csm_csm', PACKAGE = 'csm', lam1, lam2, lam3, mu1, mu2, crown_or_stem, pp, t_step)
}

